### ISSUE TITLE
Improve burger menu open/close functionality 

### ISSUE THREAD

**Issue by martinyis** [martinyis/RepoAppIdea#50]
Currently, when toggling the burger menu, there are two React icons that change depending on the state of the menu. The close icon is shifted slightly to the left, about 1-2 pixels. We need to implement a new mechanism that includes an animation for the burger open/close button and ensures that no elements are shifted. Use some library or whatever you want. And if it will take more then 20 lines create a new component for that button!

**Comment by NishantEC** [comment]
@martinyis hey, I'd like to contribute to this, can you assign me ?

**Comment by rayvalesh** [comment]
@martinyis Could you please assign this issue to me? I have implemented the necessary changes to address the problem. The burger menu now includes an animated open/close button that prevents any element shifting. I have utilized a suitable library to accomplish this task. This issue is now ready to be raised as a pull request.
